### PR TITLE
Remove library version from libldap and liblber

### LINKED ISSUE #140: Unable to use LdapForNet with libldap 2.6 on linux
**Describe the bug**
I am using the newest version of the `libldap` package on arch linux: 2.6.0-2
https://archlinux.org/packages/core/x86_64/libldap/

When I try to initialize the LdapForNet library, I get the following error:

```txt
System.DllNotFoundException: Unable to load shared library 'ldap-2.4.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libldap-2.4.so.2: cannot open shared object file: No such file or directory
   at LdapForNet.Native.NativeMethodsLinux.ldap_initialize(IntPtr& ld, String uri)
   at LdapForNet.Native.LdapNativeLinux.Init(IntPtr& ld, String url)
   at LdapForNet.LdapConnection.Connect(String url, LdapVersion version)
   at LdapForNet.LdapConnectExtensions.Connect(ILdapConnection connection, Uri uri, LdapVersion version)
   at LdapForNet.LdapConnectExtensions.Connect(ILdapConnection connection, String hostname, Int32 port, LdapSchema ldapSchema, LdapVersion version)
   at Ldap.Client..ctor(String host, Int32 port, Boolean tls, Boolean trustAll, TimeSpan timeout, Boolean chaseReferrals)
```

The filenames of the .so files are hardcoded in this library:
```c#
        private const string LIB_LDAP_PATH = "ldap-2.4.so.2";
        private const string LIB_LBER_PATH = "lber-2.4.so.2";
```
(Excerpt from "ldap4net/LdapForNet/Native/NativeMethodsLinux.cs")

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Library version: 2.7

### PR DESCRIPTION
**Pull request by joperator**
Fixes #140 and #141 by not specifying a particular version of `libldap` and `liblber` in the code, but just referencing the major version of those libraries.

### CODE REVIEW

File: LdapForNet/Native/NativeMethodsLinux.cs [hunk 1]
```diff
@@ -6,8 +6,8 @@ namespace LdapForNet.Native
 {
     internal static class NativeMethodsLinux
     {
-        private const string LIB_LDAP_PATH = "ldap-2.4.so.2";
-        private const string LIB_LBER_PATH = "lber-2.4.so.2";
+        private const string LIB_LDAP_PATH = "ldap.so.2";
```
Comment (flamencist) [inline LdapForNet/Native/NativeMethodsLinux.cs:9]: please add notes to documentation about OpenLDAP library finding on the Linux platform. So a user should create symlink "ldap.so.2" and "lber.so.2" If some Linux distributive does not have such symlink
